package com.danilorocha.app.entity;

import java.util.ArrayList;
import java.util.List;

public class CidadeUtil {
    public static List<String> cidades = new ArrayList<String>() {{
       add("Abreulândia");
       add("Aguiarnópolis");
       add("Aliança do Tocantins");
       add("Almas");
       add("Alvorada");
       add("Ananás");
       add("Angico");
       add("Aparecida do Rio Negro");
       add("Aragominas");
       add("Araguacema");
       add("Araguaçu");
       add("Araguaína");
       add("Araguanã");
       add("Araguatins");
       add("Arapoema");
       add("Arraias");
       add("Augustinópolis");
       add("Aurora do Tocantins");
       add("Axixá do Tocantins");
       add("Babaçulândia");
       add("Bandeirantes do Tocantins");
       add("Barra do Ouro");
       add("Barrolândia");
       add("Bernardo Sayão");
       add("Bom Jesus do Tocantins");
       add("Brasilândia do Tocantins");
       add("Brejinho de Nazaré");
       add("Buriti do Tocantins");
       add("Cachoeirinha");
       add("Campos Lindos");
       add("Cariri do Tocantins");
       add("Carmolândia");
       add("Carrasco Bonito");
       add("Caseara");
       add("Centenário");
       add("Chapada da Natividade");
       add("Chapada de Areia");
       add("Colinas do Tocantins");
       add("Colméia");
       add("Combinado");
       add("Conceição do Tocantins");
       add("Couto de Magalhães");
       add("Cristalândia");
       add("Crixás do Tocantins");
       add("Darcinópolis");
       add("Dianópolis");
       add("Divinópolis do Tocantins");
       add("Dois Irmãos do Tocantins");
       add("Dueré");
       add("Esperantina");
       add("Fátima");
       add("Figueirópolis");
       add("Filadélfia");
       add("Formoso do Araguaia");
       add("Fortaleza do Tabocão");
       add("Goianorte");
       add("Goiatins");
       add("Guaraí");
       add("Gurupi");
       add("Ipueiras");
       add("Itacajá");
       add("Itaguatins");
       add("Itapiratins");
       add("Itaporã do Tocantins");
       add("Jaú do Tocantins");
       add("Juarina");
       add("Lagoa da Confusão");
       add("Lagoa do Tocantins");
       add("Lajeado");
       add("Lavandeira");
       add("Lizarda");
       add("Luzinópolis");
       add("Marianópolis do Tocantins");
       add("Mateiros");
       add("Maurilândia do Tocantins");
       add("Miracema do Tocantins");
       add("Miranorte");
       add("Monte do Carmo");
       add("Monte Santo do Tocantins");
       add("Muricilândia");
       add("Natividade");
       add("Nazaré");
       add("Nova Olinda");
       add("Nova Rosalândia");
       add("Novo Acordo");
       add("Novo Alegre");
       add("Novo Jardim");
       add("Oliveira de Fátima");
       add("Palmas");
       add("Palmeirante");
       add("Palmeiras do Tocantins");
       add("Palmeirópolis");
       add("Paraíso do Tocantins");
       add("Paranã");
       add("Pau d'Arco");
       add("Pedro Afonso");
       add("Peixe");
       add("Pequizeiro");
       add("Pindorama do Tocantins");
       add("Piraquê");
       add("Pium");
       add("Ponte Alta do Bom Jesus");
       add("Ponte Alta do Tocantins");
       add("Porto Alegre do Tocantins");
       add("Porto Nacional");
       add("Praia Norte");
       add("Presidente Kennedy");
       add("Pugmil");
       add("Recursolândia");
       add("Riachinho");
       add("Rio da Conceição");
       add("Rio dos Bois");
       add("Rio Sono");
       add("Sampaio");
       add("Sandolândia");
       add("Santa Fé do Araguaia");
       add("Santa Maria do Tocantins");
       add("Santa Rita do Tocantins");
       add("Santa Rosa do Tocantins");
       add("Santa Tereza do Tocantins");
       add("Santa Terezinha do Tocantins");
       add("São Bento do Tocantins");
       add("São Félix do Tocantins");
       add("São Miguel do Tocantins");
       add("São Salvador do Tocantins");
       add("São Sebastião do Tocantins");
       add("São Valério da Natividade");
       add("Silvanópolis");
       add("Sítio Novo do Tocantins");
       add("Sucupira");
       add("Taguatinga");
       add("Taipas do Tocantins");
       add("Talismã");
       add("Tocantínia");
       add("Tocantinópolis");
       add("Tupirama");
       add("Tupiratins");
       add("Wanderlândia");
       add("Xambioá");
    }};
}
